routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

Route::get('/', function () {return view('welcome');});

Auth::routes();

// 회원가입
Route::get('/sign_up_type', function() { return view('sign.sign_up_type');});
Route::post('/sign_up_terms', function(\Illuminate\Http\Request $request) {
    return view('sign.sign_up_terms', compact('request'));
});
Route::post('/sign_up_register', function(\Illuminate\Http\Request $request) {
    return view('sign.sign_up_register', compact('request'));
});
Route::post('/sign_up_register_company', function(\Illuminate\Http\Request $request) {
    return view('sign.sign_up_register_company', compact('request'));
});

Route::get('/terms_01', function() {
    return view('sign.terms_01');
});

Route::get('/terms_02', function() {
    return view('sign.terms_02');
});

Route::get('/sign_up_type', function() {
    return view('sign.sign_up_type');
});

Route::get('/sign_up_find_id', function() {
    return view('sign.sign_up_find_id');
});

Route::get('/sign_up_find_pw', function() {
    return view('sign.sign_up_find_pw');
});

Route::post('/sign_up_find_new_pw', function(\Illuminate\Http\Request $request) {

    if (!$request->user_id) {
        return response()->redirectTo('/');
    }

    return view('sign.sign_up_find_new_pw');
});

Route::get('/sign_up_finish_sign_up', function() {
    return view('sign.sign_up_finish_sign_up');
});

Route::post('/ajaxIdCheckRequest', 'UserController@id_check')->name('Users.idcheckrequest');
Route::post('/ajaxSignUpFindId', 'UserController@SingUpFindId')->name('Users.SingUpFindId');
Route::post('/ajaxSingUpFindPassword', 'UserController@SingUpFindPassWord')->name('Users.SingUpFindPassword');

Route::post('/ajaxSingUpNewPw', 'UserController@SingUpNewPw')->name('Users.SingUpNewPw');

Route::post('/ajaxSmsSend', 'SmsController@SmsSend')->name('SmsSend');
Route::post('/ajaxSmsCheck', 'SmsController@SmsCheck')->name('SmsCheck');


// 인증 예외 처리
Route::get('/approved', function() {
    Auth::logout();
    return view('approved');
})->name('approved');

// 권한 예외 처리
Route::get('/role', function() {
    Auth::logout();
    return view('role');
})->name('role');

Route::post('/ajaxContactusCreate', 'ContactsusController@store')->name('Contactsus.create');

Route::post('/ajaxPayCallback', 'PaymentsController@payCallback')->name('Payments.paycallback');

Route::middleware(['auth', 'approved','role'])->group( function () {

    Route::get('/dashboard', 'DashBoardController@index')->name('dashboard.index');

    // 마이데이터(order)
    Route::resource('goods' , 'GoodsController');
    Route::resource('carts' , 'CartController');
    Route::post('/ajaxFindCart' , 'CartController@findById')->name('carts.findById');


    // 마이데이터 플랫폼(option)
    Route::post('/ajaxOptionAdd','OptionController@optionAdd')->name('Option.add');
    Route::post('/ajaxOptionSave','OptionController@optionSave')->name('Option.save');
    Route::post('/ajaxOptionUploadRequest','OptionController@optionUploadRequest')->name('Option.updateload');

    // payment
    Route::post('/ajaxPayRequest', 'PaymentsController@payRequest')->name('Payments.payrequest');
    Route::post('/ajaxPayReturn', 'PaymentsController@payReturn')->name('Payments.payreturn');

    Route::get('/ajaxPayCancel', 'PaymentsController@payCancel')->name('Payments.payCancel');

    // 자주묻는질문(faq)
    Route::resources(['faqs' => 'FaqController']);

    // 문의및답변(qna)
    Route::resources(['questions' => 'QuestionController']);

    // 세금계산서요청(tax)
    Route::get('taxs', function () { return view('taxs.index'); });

    // 내정보 수정(users)
    Route::get('users', function () { return view('users.index'); });

    Route::get('users/confirm', 'UserController@confirm_index')->name('confirm_index');
    Route::post('users/confirm_check', 'UserController@confirm_check')->name('confirm_check');
    Route::post('my_show', 'UserController@my_show')->name('my_show');
    Route::post('my_update', 'UserController@my_update')->name('my_update');
    Route::get('file_download/{file_name}', 'UserController@file_download')->name('file_download');

    // 주문내역
    Route::get('/history', 'OrderController@history')->name('orders_history');
    Route::post('/ajaxFindOrder', 'OrderController@findById')->name('orders.findById');
    Route::post('/ajaxTaxState', 'OrderController@taxstate')->name('tax_state');

    // payment_test_page
    Route::get('/payment', function () {
        return view('payment');
    })->name('Payments.index');


});

app/Faq.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Faq extends Model
{
    protected $fillable = [
        'title', 'content',
    ];

    protected $guarded = [];

    public function format()
    {
        return [
            'faq_id' => $this->id,
            'name' => $this->user->name,
            'title' => $this->title,
            'content' => $this->content,
            'email' => $this->user->email,
            'last_update' => $this->updated_at->diffForHumans()
        ];
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/FaqController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\FaqRepositoryInterface;
use Illuminate\Http\Request;

class FaqController extends Controller
{
    private $faqRepository;

    public function __construct(FaqRepositoryInterface $faqRepository)
    {
        $this->faqRepository = $faqRepository;
    }

    public function index()
    {
        $faqs = $this->faqRepository->all();

        return view('faqs.index', compact('faqs'));
    }

    public function create()
    {
        return view('faqs.create');
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'title' => 'required',
            'content' => 'required',
        ]);
        $this->faqRepository->create($validatedData);

        return redirect()->route('faqs.index');
    }

    public function show($id)
    {
        $faq = $this->faqRepository->findById($id);

        return view('faqs.show', compact('faq'));
    }

    public function edit($id)
    {
        $faq = $this->faqRepository->findById($id);

        return view('faqs.edit', compact('faq'));
    }

    public function update(Request $request, $id)
    {
        $this->faqRepository->update($request, $id);

        return redirect()->route('faqs.index');
    }

    public function destroy($id)
    {
        $this->faqRepository->destory($id);

        return redirect()->route('faqs.index');
    }
}

resources/views/faqs/create.blade.php
@extends('dashboard')

@section('content')

            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Faq Create</div>

                    <div class="card-body">

                        <form method="POST" action="{{ route('faqs.store') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="title" class="col-md-4 col-form-label text-md-right">Title</label>

                                <div class="col-md-6">
                                    <input id="title" type="text" class="form-control  @error('title') is-invalid @enderror" name="title" value="" autocomplete="name">

                                    @error('title')
                                    <span class="text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="content" class="col-md-4 col-form-label text-md-right">Content</label>

                                <div class="col-md-6">
                                    <input id="content" type="text" class="form-control  @error('content') is-invalid @enderror" name="content" value="" autocomplete="content">

                                    @error('content')
                                    <span class="text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        저장하기
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

@endsection

resources/views/faqs/edit.blade.php
@extends('dashboard')

@section('content')

            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Post Create</div>

                    <div class="card-body">

                        <form method="POST" action="{{ route('faqs.update', $faq['faq_id']) }}">
                            @csrf
                            @method('PUT')

                            <div class="form-group row">
                                <label for="title" class="col-md-4 col-form-label text-md-right">Title</label>

                                <div class="col-md-6">
                                    <input id="title" type="text" class="form-control  @error('title') is-invalid @enderror" name="title" value="{{ $faq['title'] }}" autocomplete="name">

                                    @error('title')
                                    <span class="text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="content" class="col-md-4 col-form-label text-md-right">Content</label>

                                <div class="col-md-6">
                                    <input id="content" type="text" class="form-control  @error('content') is-invalid @enderror" name="content" value="{{ $faq['content'] }}" autocomplete="content">

                                    @error('content')
                                    <span class="text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        수정하기
                                    </button>
                                </div>
                            </div>
                        </form>

                    </div>
                </div>
            </div>

@endsection

resources/views/faqs/index.blade.php
@extends('layouts.backend')

@section('content')

    <div class="container-fluid flex-grow-1 container-p-y question">

        <div class="wrap">
            <div class="top">
                자주 묻는 질문
                <span class="txt">DMP9에게 궁금한 점을 쉽고 빠르게 찾아보세요.</span>
            </div>
            <div class="cont">
                <div class="top">목록</div>
                @foreach($faqs as $faq)
                <ul>
                    <li class="text_question">
                        <p>
                            Q. {{ $faq['title'] }}
                        </p>
                        <span><img src="./assets/img/btn_arrow_down.png" alt="화살표 아래"/></span>
                    </li>
                    <li class="text_answer">
                        <span class="index">A.</span>
                        <span class="txt">
                           {{ $faq['content'] }}
                        </span>
                    </li>
                </ul>
                @endforeach
            </div>


        </div>
    </div>



@endsection

resources/views/faqs/show.blade.php
@extends('dashboard')

@section('content')

            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Faq Create</div>

                    <div class="card-body">



                            <div class="form-group row">
                                <label for="title" class="col-md-4 col-form-label text-md-right">Title</label>

                                <div class="col-md-6">
                                    {{ $faq['title'] }}
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="content" class="col-md-4 col-form-label text-md-right">Content</label>

                                <div class="col-md-6">
                                    {{ $faq['content'] }}
                                </div>
                            </div>


                        <a class="btn btn-primary" href="{{ route('faqs.edit', $faq['faq_id']) }}" role="button">수정하기</a>

                        <form method="POST" action="{{ route('faqs.destroy', $faq['faq_id']) }}">
                            @csrf
                            @method('DELETE')

                            <button type="submit" class="btn btn-danger">
                                삭제
                            </button>
                        </form>
                    </div>
                </div>
            </div>

@endsection