routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

Route::get('/', function () {return view('welcome');});

Auth::routes();

// 회원가입
Route::get('/sign_up_type', function() { return view('sign.sign_up_type');});
Route::post('/sign_up_terms', function(\Illuminate\Http\Request $request) {
    return view('sign.sign_up_terms', compact('request'));
});
Route::post('/sign_up_register', function(\Illuminate\Http\Request $request) {
    return view('sign.sign_up_register', compact('request'));
});
Route::post('/sign_up_register_company', function(\Illuminate\Http\Request $request) {
    return view('sign.sign_up_register_company', compact('request'));
});

Route::get('/terms_01', function() {
    return view('sign.terms_01');
});

Route::get('/terms_02', function() {
    return view('sign.terms_02');
});

Route::get('/sign_up_type', function() {
    return view('sign.sign_up_type');
});

Route::get('/sign_up_find_id', function() {
    return view('sign.sign_up_find_id');
});

Route::get('/sign_up_find_pw', function() {
    return view('sign.sign_up_find_pw');
});

Route::post('/sign_up_find_new_pw', function(\Illuminate\Http\Request $request) {

    if (!$request->user_id) {
        return response()->redirectTo('/');
    }

    return view('sign.sign_up_find_new_pw');
});

Route::get('/sign_up_finish_sign_up', function() {
    return view('sign.sign_up_finish_sign_up');
});

Route::post('/ajaxIdCheckRequest', 'UserController@id_check')->name('Users.idcheckrequest');
Route::post('/ajaxSignUpFindId', 'UserController@SingUpFindId')->name('Users.SingUpFindId');
Route::post('/ajaxSingUpFindPassword', 'UserController@SingUpFindPassWord')->name('Users.SingUpFindPassword');

Route::post('/ajaxSingUpNewPw', 'UserController@SingUpNewPw')->name('Users.SingUpNewPw');

Route::post('/ajaxSmsSend', 'SmsController@SmsSend')->name('SmsSend');
Route::post('/ajaxSmsCheck', 'SmsController@SmsCheck')->name('SmsCheck');


// 인증 예외 처리
Route::get('/approved', function() {
    Auth::logout();
    return view('approved');
})->name('approved');

// 권한 예외 처리
Route::get('/role', function() {
    Auth::logout();
    return view('role');
})->name('role');

Route::post('/ajaxContactusCreate', 'ContactsusController@store')->name('Contactsus.create');

Route::post('/ajaxPayCallback', 'PaymentsController@payCallback')->name('Payments.paycallback');

Route::middleware(['auth', 'approved','role'])->group( function () {

    Route::get('/dashboard', 'DashBoardController@index')->name('dashboard.index');

    // 마이데이터(order)
    Route::resource('goods' , 'GoodsController');
    Route::resource('carts' , 'CartController');
    Route::post('/ajaxFindCart' , 'CartController@findById')->name('carts.findById');


    // 마이데이터 플랫폼(option)
    Route::post('/ajaxOptionAdd','OptionController@optionAdd')->name('Option.add');
    Route::post('/ajaxOptionSave','OptionController@optionSave')->name('Option.save');
    Route::post('/ajaxOptionUploadRequest','OptionController@optionUploadRequest')->name('Option.updateload');

    // payment
    Route::post('/ajaxPayRequest', 'PaymentsController@payRequest')->name('Payments.payrequest');
    Route::post('/ajaxPayReturn', 'PaymentsController@payReturn')->name('Payments.payreturn');

    Route::get('/ajaxPayCancel', 'PaymentsController@payCancel')->name('Payments.payCancel');

    // 자주묻는질문(faq)
    Route::resources(['faqs' => 'FaqController']);

    // 문의및답변(qna)
    Route::resources(['questions' => 'QuestionController']);

    // 세금계산서요청(tax)
    Route::get('taxs', function () { return view('taxs.index'); });

    // 내정보 수정(users)
    Route::get('users', function () { return view('users.index'); });

    Route::get('users/confirm', 'UserController@confirm_index')->name('confirm_index');
    Route::post('users/confirm_check', 'UserController@confirm_check')->name('confirm_check');
    Route::post('my_show', 'UserController@my_show')->name('my_show');
    Route::post('my_update', 'UserController@my_update')->name('my_update');
    Route::get('file_download/{file_name}', 'UserController@file_download')->name('file_download');

    // 주문내역
    Route::get('/history', 'OrderController@history')->name('orders_history');
    Route::post('/ajaxFindOrder', 'OrderController@findById')->name('orders.findById');
    Route::post('/ajaxTaxState', 'OrderController@taxstate')->name('tax_state');

    // payment_test_page
    Route::get('/payment', function () {
        return view('payment');
    })->name('Payments.index');


});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
//    protected $fillable = [
//        'name', 'email', 'password','approved','approved_at'
//    ];

    protected $guarded = ['*','id'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function goods()
    {
        return $this->hasMany(Goods::class);
    }

    public function carts()
    {
        return $this->hasMany(Cart::class)->orderBy('id','desc');
    }

    public function orders()
    {
        return $this->hasMany(Order::class);
    }

    public function faqs()
    {
        return $this->hasMany(Faq::class);
    }

    public function questions()
    {
        return $this->hasMany(Question::class);
    }

    public function payment_returns()
    {
        return $this->hasMany(Payment_return::class);
    }

    public function taxes()
    {
        return $this->hasMany(Tax::class);
    }

    public function options()
    {
        return $this->hasMany(Option::class);
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Mail\SendMailable;
use App\Repositories\TaxRepositoryInterface;
use App\Repositories\UserRepositoryInterface;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;
use Illuminate\Support\Facades\Storage;

class UserController extends Controller
{
    private $userRepository;
    private $taxRepository;

    public function __construct(UserRepositoryInterface $userRepository, TaxRepositoryInterface $taxRepository)
    {
        $this->middleware(['auth', 'approved','role'], ['except' => ['id_check', 'SingUpFindId', 'SingUpNewPw', 'SingUpFindPassWord']]);
        $this->userRepository = $userRepository;
        $this->taxRepository = $taxRepository;
    }

    // 마이정보-패스워드입력 화면
    public function confirm_index()
    {
        return view('users.confirm_index');
    }

    // 마이정보-비밀번호체크
    public function confirm_check(Request $request)
    {
        $request_data = json_decode($request->data);

        $result['result'] = "success";

        if (!$this->userRepository->password_check($request_data)) {
            $result['result'] = "error";
            $result['error_message'] = "패스워드를 다시 입력 해주세요.";
        }

        $response = response()->json($result, 200, ['Content-type'=> 'application/json; charset=utf-8'], JSON_UNESCAPED_UNICODE);

        return $response;
    }

    // 마이정보-수정입력 화면
    public function my_show()
    {
        $user = $this->userRepository->findById();
        $taxs = $user->taxes;

        if (!is_array($taxs)) {
            $taxs[] = '';
        }

        return view('users.company', compact('user','taxs'));
    }

    public function file_download($file_name)
    {
        $path = storage_path(). "/app/tax/".auth()->user()->user_id."/".$file_name;

        return response()->download($path);
    }

    // 마이정보-수정 업데이트
    public function my_update(Request $request)
    {
        $request['password'] = $this->userRepository->makePassword($request['password']);

        $this->userRepository->update($request);

//        if ($request['type'] == "company") {
//            $this->taxRepository->update($request);
//        }

        return redirect('users')->with('alert','정상적으로 수정 되었습니다.');
    }

    // 회원가입-아이디체크
    public function id_check(Request $request)
    {
        $user_id = $this->userRepository->findByUserId($request->data);
        $result = response()->json(['result'=> $user_id], 200, ['Content-type'=> 'application/json; charset=utf-8'], JSON_UNESCAPED_UNICODE);

        return $result;
    }

    // 아이디 찾기
    public function SingUpFindId(Request $request)
    {
        $request_data = json_decode($request->data);
        $return_result = $this->userRepository->SingUpFindId($request_data);

        if (empty($return_result[0])) {
            $result['result'] = "error";
            $result['error_message'] = "전송 실패";
            $response = response()->json($result, 200, ['Content-type'=> 'application/json; charset=utf-8'], JSON_UNESCAPED_UNICODE);
        } else {
            $result['result'] = "success";
            $result['result_info'] = $return_result;
            $response = response()->json($result, 200, ['Content-type'=> 'application/json; charset=utf-8'], JSON_UNESCAPED_UNICODE);
        }

        return $response;
    }

    public function SingUpFindPassWord(Request $request)
    {
        $request_data = json_decode($request->data);
        $return_result = $this->userRepository->SingUpFindById($request_data);

        if (empty($return_result[0])) {
            $result['result'] = "error";
            $result['error_message'] = "전송 실패";
            $response = response()->json($result, 200, ['Content-type'=> 'application/json; charset=utf-8'], JSON_UNESCAPED_UNICODE);
        } else {
            Mail::to($return_result[0]['email'])->send(new SendMailable($return_result[0]));

            $result['result'] = "success";
            $result['result_info'] = $return_result;
            $response = response()->json($result, 200, ['Content-type'=> 'application/json; charset=utf-8'], JSON_UNESCAPED_UNICODE);
        }

        return $response;
    }

    public function SingUpNewPw(Request $request)
    {
        $request_data = json_decode($request->data);
        $return_result = $this->userRepository->SingUpNewPw($request_data);

        if (!$return_result) {
            $result['result'] = "error";
            $result['error_message'] = "전송 실패";
            $response = response()->json($result, 200, ['Content-type'=> 'application/json; charset=utf-8'], JSON_UNESCAPED_UNICODE);
        } else {
            $result['result'] = "success";
            $result['result_info'] = $return_result;
            $response = response()->json($result, 200, ['Content-type'=> 'application/json; charset=utf-8'], JSON_UNESCAPED_UNICODE);
        }

        return $response;
    }
}

resources/views/users/company.blade.php
@extends('layouts.backend')

@prepend('scripts')
    <script>
        function maxLengthCheck(object){
            if (object.value.length > object.maxLength){
                object.value = object.value.slice(0, object.maxLength);
            }
        }
        $(function() {
            $("[name=password_confirmation]").keyup(function(){
                if ($("[name=password]").val() != $("[name=password_confirmation]").val()) {
                    // false
                    $("[name=password_check]").val('no');
                    $("[name=passcheck_state_yes]").css('display','none');
                    $("[name=passcheck_state_no]").css('display','block');
                }else{
                    // true
                    $("[name=password_check]").val('yes');
                    $("[name=passcheck_state_yes]").css('display','block');
                    $("[name=passcheck_state_no]").css('display','none');
                }
            });
            $("button[name=btn_submit]").click(function() {
                if ($("input[name=name]").val() == "") {
                    alert('이름을 입력하세요.');
                    return false;
                }
                if ($("input[name=company_name]").val() == "") {
                    alert('회사명을 입력하세요.');
                    return false;
                }
                if ($("input[name=email_id]").val() == "") {
                    alert('이메일을 입력하세요.');
                    return false;
                }
                if ($("input[name=email_text]").val() == "") {
                    alert('이메일을 입력하세요.');
                    return false;
                }
                if ($("input[name=phone_1]").val() == "") {
                    alert('전화번호를 입력하세요.');
                    return false;
                }
                if ($("input[name=phone_2]").val() == "") {
                    alert('전화번호를 입력하세요.');
                    return false;
                }
                if ($("input[name=phone_3]").val() == "") {
                    alert('전화번호를 입력하세요.');
                    return false;
                }
                $("form[name=user]").submit();
            });
        });
    </script>
@endprepend

@section('content')

    <div class="container-fluid flex-grow-1 container-p-y edit_my_info">

        <div class="wrap">
            <div class="top">
                내정보 수정
                <!-- <span class="txt">DMP9에게 궁금한 점을 쉽고 빠르게 찾아보세요.</span> -->
            </div>
            <div class="cont">

                <div class="inner">
                    <form name="user" method="POST" action="{{ route('my_update') }}" enctype="multipart/form-data">
                        @csrf
                        <input type="hidden" name="type" value="{{ $user->role }}">

                        <div class="title">기본정보</div>
                        <div class="edit_wrap">
                            <div class="input-group first_radius">
                                <div class="label_box">
                                    <label>이름</label>
                                </div>
                                <div class="input_box">
                                    <input type="text"  placeholder="" name="name" value="{{ $user->name }}" style="color: #ccc" readonly />
                                </div>
                            </div>
                            <div class="input-group">
                                <div class="label_box">
                                    <label>아이디</label>
                                </div>
                                <div class="input_box">
                                    <input type="text" placeholder="" name="user_id" value="{{ $user->user_id }}" style="color: #ccc" disabled/>
                                </div>
                            </div>
                            <div class="input-group">
                                <div class="label_box">
                                    <label>비밀번호</label>
                                </div>
                                <div class="input_box">
                                    <input type="password" placeholder="영문,숫자 포함 8~12자를 입력해주세요" name="password" autocomplete="off" />
                                </div>
                            </div>
                            <div class="input-group">
                                <div class="label_box">
                                    <label>비밀번호 확인</label>
                                </div>
                                <div class="input_box">
                                    <input type="password" placeholder="영문,숫자 포함 8~12자를 입력해주세요" name="password_confirmation" autocomplete="off"  />
                                    <div class="message_group">
                                        <div class="check_state_yes" name="passcheck_state_yes" style="display: none;">비밀번호가 일치합니다.</div>
                                        <div class="check_state_no" name="passcheck_state_no" style="display: none;">비밀번호가 일치하지 않습니다.</div>
                                    </div>
                                </div>
                            </div>
                            <div class="input-group">
                                <div class="label_box">
                                    <label>회사명</label>
                                </div>
                                <div class="input_box">
                                    <input type="text" placeholder="" name="company_name" value="{{ $user->company_name }}" autocomplete="off" />
                                </div>
                            </div>
                            <div class="input-group">
                                <div class="label_box">
                                    <label>이메일</label>
                                </div>
                                <div class="input_box">
                                    <input type="text" placeholder="" name="email" id="email" value="{{ $user->email }}" autocomplete="off" />
                                </div>
                            </div>
                            <div class="input-group last_radius">
                                <div class="label_box">
                                    <label>연락처</label>
                                </div>
                                <div class="input_box">
                                    <input type="number" placeholder="연락처를 입력해주세요 (ex. 01012345678910)" name="phone" id="phone" value="{{ $user->phone }}" autocomplete="off" />
                                </div>
                            </div>

                            @if ($taxs[0])
                            <!--사업자정보-->
                            <div class="title company_title ">
                                사업계산서 수정
                                <span class="txt"> - 사업자 정보 수정은 <br class="mo_br"/>관리자 승인 후 변경 가능 합니다. </span>
                                <button type="button" onclick="location.href = '/questions';">수정요청</button>
                            </div>

                            <div class="input-group first_radius input_disabled">
                                <div class="label_box">
                                    <label>사업자등록번호</label>
                                </div>
                                <div class="input_box">
                                    <input type="text" placeholder="" name="tax_company_number" value="{{$taxs[0]['tax_company_number']}}" style="color: #ccc" disabled/>
                                </div>
                            </div>
                            <div class="input-group input_disabled">
                                <div class="label_box">
                                    <label>업체명(법인명)</label>
                                </div>
                                <div class="input_box">
                                    <input type="text" placeholder="" name="tax_company_name" value="{{$taxs[0]['tax_company_name']}}" style="color: #ccc" disabled/>
                                </div>
                            </div>
                            <div class="input-group input_disabled">
                                <div class="label_box">
                                    <label>대표자명</label>
                                </div>
                                <div class="input_box">
                                    <input type="text" placeholder="" name="tax_name" value="{{$taxs[0]['tax_name']}}" style="color: #ccc" disabled />
                                </div>
                            </div>
                            <div class="input-group input_disabled">
                                <div class="label_box">
                                    <label>주소</label>
                                </div>
                                <div class="input_box">
                                    <div class="address_box form-inline">
                                        <input type="text" id="postcode" class="postcode form-control form-control2" placeholder="우편번호를 입력해주세요" name="tax_zipcode" value="{{$taxs[0]['tax_zipcode']}}" style="color: #ccc" disabled>

                                        <input type="text" id="address" class="address form-control" placeholder="기본주소를 검색하세요" name="tax_addres_1" value="{{$taxs[0]['tax_addres_1']}}" style="color: #ccc" disabled>
                                        <input type="text" id="detailAddress" class="detailAddress form-control" placeholder="상세주소를 입력해주세요" name="tax_addres_2" value="{{$taxs[0]['tax_addres_2']}}" style="color: #ccc" disabled>
                                        <input type="text" id="extraAddress" class="extraAddress form-control" placeholder="참고항목">
                                    </div>
                                </div>
                            </div>
                            <div class="input-group last_radius input_disabled">
                                <div class="label_box">
                                    <label>사업자등록증</label>
                                </div>
                                <div class="input_box">
                                    <a target="_blank" href="https://dmp9storage1.blob.core.windows.net/images/tax/{{$user->user_id}}/{{$taxs[0]['tax_img']}}">{{$taxs[0]['tax_img']}}</a>
                                </div>
                            </div>
                            @endif
                        </div>
                        <!--사업자정보-->

                        <div class="but_box mt-4">
                            <button type="button" name="btn_submit">회원정보수정</button>
                            <button type="button" onclick="location.href='/carts'">취소</button>
                        </div>
                    </form>
                </div>

            </div>
        </div>

    </div>



@endsection

resources/views/users/confirm_index.blade.php
@extends('layouts.backend')

@section('content')

            <div class="col-md-8">
                <div class="card">
                    <div class="card-header"></div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('confirm_check') }}">
                            @csrf

                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">비밀번호</label>

                                <div class="col-md-6">
                                    <input id="current_password" type="password" class="form-control @error('current_password') is-invalid @enderror" name="current_password" value="" required autocomplete="current_password" autofocus>

                                    @error('current_password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong></strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>


                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        확인
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>

@endsection

resources/views/users/index.blade.php
@extends('layouts.backend')

@prepend('scripts')
    <script>
    $(function() {
        $("#current_password").keydown(function(key) {
            if (key.keyCode == 13) {
                var data = new Object();
                data.password = $("#current_password").val();
                var jsonData = JSON.stringify(data);

                $.ajax({
                    headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                    url: "{{ route('confirm_check') }}",
                    method: "POST",
                    dataType: "json",
                    data: {'data': jsonData},
                    success: function (data) {
                        var JSONArray = JSON.parse(JSON.stringify(data));
                        if (JSONArray['result'] == "success") {
                            $("form[name='frm']").attr("onsubmit", "return true");
                            $("form[name='frm']").attr("action", "{{ route('my_show') }}");
                            $("form[name='frm']").submit();
                        } else if (JSONArray['result'] == "error") {
                            alert(JSONArray['error_message']);
                        };
                    },
                    error: function () {
                        alert("Error while getting results");
                    }
                });
            }
        });
    });
    </script>
@endprepend


@if(session()->has('alert'))
    <script>
        alert('정상적으로 수정 되었습니다.');
        location.href = "{{ route('carts.index') }}";
    </script>
@endif

@section('content')
    <!-- content : start-->
    <div class="container-fluid flex-grow-1 container-p-y edit_my_information">
        <div class="wrap">
            <form name="frm" method="post" onsubmit="return false"  action="">
                @csrf
                <div class="inner">
                    <div class="text_box">
                        <div class="img_box">
                            <img src="/assets/img/icon_lock.png" alt="아이콘 자물쇠"/>
                        </div>
                        <p>입력창에 비밀번호를 입력해 주세요.</p>
                        <p>개인 정보를 수정하실 수 있습니다.</p>
                    </div>
                    <div class="input_box">
                        <input id="current_password" type="password" class="@error('current_password') is-invalid @enderror" placeholder="비밀번호를 입력하세요" name="current_password" autocomplete="off" required>
                        @error('current_password')
                        <span class="invalid-feedback" role="alert">
                        <strong></strong>
                        </span>
                        @enderror
                    </div>
                </div>
            </form>
        </div>
    </div>
    <!-- content : end-->
@endsection