routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

Route::get('/', function () {return view('welcome');});

Auth::routes();

// 회원가입
Route::get('/sign_up_type', function() { return view('sign.sign_up_type');});
Route::post('/sign_up_terms', function(\Illuminate\Http\Request $request) {
    return view('sign.sign_up_terms', compact('request'));
});
Route::post('/sign_up_register', function(\Illuminate\Http\Request $request) {
    return view('sign.sign_up_register', compact('request'));
});
Route::post('/sign_up_register_company', function(\Illuminate\Http\Request $request) {
    return view('sign.sign_up_register_company', compact('request'));
});

Route::get('/terms_01', function() {
    return view('sign.terms_01');
});

Route::get('/terms_02', function() {
    return view('sign.terms_02');
});

Route::get('/sign_up_type', function() {
    return view('sign.sign_up_type');
});

Route::get('/sign_up_find_id', function() {
    return view('sign.sign_up_find_id');
});

Route::get('/sign_up_find_pw', function() {
    return view('sign.sign_up_find_pw');
});

Route::post('/sign_up_find_new_pw', function(\Illuminate\Http\Request $request) {

    if (!$request->user_id) {
        return response()->redirectTo('/');
    }

    return view('sign.sign_up_find_new_pw');
});

Route::get('/sign_up_finish_sign_up', function() {
    return view('sign.sign_up_finish_sign_up');
});

Route::post('/ajaxIdCheckRequest', 'UserController@id_check')->name('Users.idcheckrequest');
Route::post('/ajaxSignUpFindId', 'UserController@SingUpFindId')->name('Users.SingUpFindId');
Route::post('/ajaxSingUpFindPassword', 'UserController@SingUpFindPassWord')->name('Users.SingUpFindPassword');

Route::post('/ajaxSingUpNewPw', 'UserController@SingUpNewPw')->name('Users.SingUpNewPw');

Route::post('/ajaxSmsSend', 'SmsController@SmsSend')->name('SmsSend');
Route::post('/ajaxSmsCheck', 'SmsController@SmsCheck')->name('SmsCheck');


// 인증 예외 처리
Route::get('/approved', function() {
    Auth::logout();
    return view('approved');
})->name('approved');

// 권한 예외 처리
Route::get('/role', function() {
    Auth::logout();
    return view('role');
})->name('role');

Route::post('/ajaxContactusCreate', 'ContactsusController@store')->name('Contactsus.create');

Route::post('/ajaxPayCallback', 'PaymentsController@payCallback')->name('Payments.paycallback');

Route::middleware(['auth', 'approved','role'])->group( function () {

    Route::get('/dashboard', 'DashBoardController@index')->name('dashboard.index');

    // 마이데이터(order)
    Route::resource('goods' , 'GoodsController');
    Route::resource('carts' , 'CartController');
    Route::post('/ajaxFindCart' , 'CartController@findById')->name('carts.findById');


    // 마이데이터 플랫폼(option)
    Route::post('/ajaxOptionAdd','OptionController@optionAdd')->name('Option.add');
    Route::post('/ajaxOptionSave','OptionController@optionSave')->name('Option.save');
    Route::post('/ajaxOptionUploadRequest','OptionController@optionUploadRequest')->name('Option.updateload');

    // payment
    Route::post('/ajaxPayRequest', 'PaymentsController@payRequest')->name('Payments.payrequest');
    Route::post('/ajaxPayReturn', 'PaymentsController@payReturn')->name('Payments.payreturn');

    Route::get('/ajaxPayCancel', 'PaymentsController@payCancel')->name('Payments.payCancel');

    // 자주묻는질문(faq)
    Route::resources(['faqs' => 'FaqController']);

    // 문의및답변(qna)
    Route::resources(['questions' => 'QuestionController']);

    // 세금계산서요청(tax)
    Route::get('taxs', function () { return view('taxs.index'); });

    // 내정보 수정(users)
    Route::get('users', function () { return view('users.index'); });

    Route::get('users/confirm', 'UserController@confirm_index')->name('confirm_index');
    Route::post('users/confirm_check', 'UserController@confirm_check')->name('confirm_check');
    Route::post('my_show', 'UserController@my_show')->name('my_show');
    Route::post('my_update', 'UserController@my_update')->name('my_update');
    Route::get('file_download/{file_name}', 'UserController@file_download')->name('file_download');

    // 주문내역
    Route::get('/history', 'OrderController@history')->name('orders_history');
    Route::post('/ajaxFindOrder', 'OrderController@findById')->name('orders.findById');
    Route::post('/ajaxTaxState', 'OrderController@taxstate')->name('tax_state');

    // payment_test_page
    Route::get('/payment', function () {
        return view('payment');
    })->name('Payments.index');


});

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Question extends Model
{
//    protected $fillable = [
//        'title', 'content',
//    ];

    protected $guarded = ['*','id'];

    public function format()
    {
        return [
            'question_id' => $this->id,
            'name' => $this->user->name,
            'title' => $this->title,
            'content' => $this->content,
            'email' => $this->user->email,
            'last_update' => $this->updated_at->diffForHumans(),
            'answers' => $this->answers,
        ];
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function answers()
    {
        return $this->hasMany(Answer::class);
    }
}

app/Http/Controllers/QuestionController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\QuestionRepositoryInterface;
use Illuminate\Http\Request;

class QuestionController extends Controller
{
    private $questionRepository;

    public function __construct(QuestionRepositoryInterface $questionRepository)
    {
        $this->questionRepository = $questionRepository;
    }

    public function index()
    {
        $questions = $this->questionRepository->all();

        $count = $questions->total();
        return view('questions.index', compact('questions', 'count'));
    }

    public function create()
    {
        return view('questions.create');
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'name' => 'required',
            'title' => 'required',
            'content' => 'required',
            'email' => 'required',
            'phone' => 'required',
        ]);

        $this->questionRepository->create($validatedData);

        return redirect()->route('questions.index');
    }

    public function show($id)
    {
        $question = $this->questionRepository->findById($id);

        return view('questions.show', compact('question'));
    }

    public function edit($id)
    {
        $question = $this->questionRepository->findById($id);

        return view('questions.edit', compact('question'));
    }

    public function update(Request $request, $id)
    {
        $this->questionRepository->update($request, $id);

        return redirect()->route('questions.index');
    }

    public function destroy($id)
    {
        $this->questionRepository->destory($id);

        return redirect()->route('questions.index');
    }
}

resources/views/questions/create.blade.php
@extends('dashboard')

@section('content')

    <div class="col-md-8">
        <div class="card">
            <div class="card-header">Questions Create</div>

            <div class="card-body">

                <form method="POST" action="{{ route('questions.store') }}">
                    @csrf

                    <div class="form-group row">
                        <label for="title" class="col-md-4 col-form-label text-md-right">Title</label>

                        <div class="col-md-6">
                            <input id="title" type="text" class="form-control  @error('title') is-invalid @enderror" name="title" value="" autocomplete="name">

                            @error('title')
                            <span class="text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="content" class="col-md-4 col-form-label text-md-right">Content</label>

                        <div class="col-md-6">
                            <input id="content" type="text" class="form-control  @error('content') is-invalid @enderror" name="content" value="" autocomplete="content">

                            @error('content')
                            <span class="text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                저장하기
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/questions/edit.blade.php
@extends('dashboard')

@section('content')

    <div class="col-md-8">
        <div class="card">
            <div class="card-header">Post Create</div>

            <div class="card-body">

                <form method="POST" action="{{ route('questions.update', $question['question_id']) }}">
                    @csrf
                    @method('PUT')

                    <div class="form-group row">
                        <label for="title" class="col-md-4 col-form-label text-md-right">Title</label>

                        <div class="col-md-6">
                            <input id="title" type="text" class="form-control  @error('title') is-invalid @enderror" name="title" value="{{ $question['title'] }}" autocomplete="name">

                            @error('title')
                            <span class="text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="content" class="col-md-4 col-form-label text-md-right">Content</label>

                        <div class="col-md-6">
                            <input id="content" type="text" class="form-control  @error('content') is-invalid @enderror" name="content" value="{{ $question['content'] }}" autocomplete="content">

                            @error('content')
                            <span class="text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                수정하기
                            </button>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div>

@endsection

resources/views/questions/index.blade.php
@extends('layouts.backend')

@prepend('scripts')
    <script>

        function validateEmail(sEmail) {
            var filter = /^([\w-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([\w-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$/;
            if (filter.test(sEmail)) {
                return true;
            }
            else {
                return false;
            }
        };

        $('#frm button[name=btn]').click(function(){
            if ($("#frm input[name=name]").val() == "") {
                alert('이름을 입력하세요.');
                return false;
            }

            if ($("#frm input[name=title]").val() == "") {
                alert('제목을 입력하세요.1');
                return false;
            }

            if ($("#frm [name=content]").val() == "") {
                alert('내용을 입력하세요.');
                return false;
            }

            if ($("#frm input[name=phone]").val() == "") {
                alert('연락처를 입력하세요.');
                return false;
            }

            if ($("#frm input[name=email]").val() == "") {
                alert('이메일을 입력하세요.');
                return false;
            }

            var sEmail = $("#frm input[name=email]").val();

            if (!validateEmail(sEmail)) {
                alert('잘못된 이메일 형식 입니다');
                return false;
            }

            if ($("#frm input:checkbox[name=check]").is(":checked") == false) {
                alert('개인정보 수집 동의 확인 후 가능합니다.');
                return false;
            }

            $('#frm').submit();
        });


    </script>

@endprepend

@section('content')
    <div class="container-fluid flex-grow-1 container-p-y contact_us">
        <div class="wrap">
            <div class="top clearfix">
                <p>문의하기
                    <span class="txt">DMP9에게 궁금한 점을 쉽고 빠르게 찾아보세요.</span>
                </p>
                <button type="button" onclick="addWriting()">글쓰기</button>
            </div>
            <div class="table_wrap">
                <table class="table">
                    <colgroup>
                        <col width="5%">
                        <col width="40%">
                        <col width="10%">
                        <col width="15%">
                        <col width="15%">
                        <col width="5%">
                    </colgroup>
                    <thead>
                    <tr>
                        <th>번호</th>
                        <th>제목</th>
                        <th>작성자</th>
                        <th>작성일</th>
                        <th>진행상태</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>

                    @foreach($questions as $question)

                    <tr>
                        <td>{{ $count }}</td>
                        <td>{{ $question['title'] }}</td>
                        <td>{{ $question['name'] }}</td>
                        <td>{{ $question['created_at']->format('Y.m.d') }}</td>
                        <td>
                            @if (!$question['answers']->isEmpty())
                                <p>완료</p>
                            @else
                                <p>대기중</p>
                            @endif
                        </td>
                        <td class="toggle_tr"><img src="./assets/img/icon_down_arrow.png" alt="아이콘 아래 화살표"/></td>
                    </tr>
                    <tr class="toggle_dropdown_tr">
                        <td colspan="6">
                            <!--itme 묶음-->
                            <div class="item mb-1">
                                <div class="txt-box form-inline">
                                    <div class="label">질문</div>
                                    <div class="txt">{{ $question['content'] }}</div>
                                </div>
                                @if (!$question['answers']->isEmpty())
                                <div class="txt-box form-inline">
                                    <div class="label">답변</div>
                                    <div class="txt">
                                         @foreach ($question['answers'] as $answer)
                                            {{ $answer['content'] }}
                                        @endforeach
                                    </div>
                                </div>
                                @endif
                            </div>
                            <!--itme 묶음-->
                        </td>
                    </tr>
                    <?php $count--; ?>
                    @endforeach
                    @if ($questions->isEmpty())
                        <tr>
                            <td colspan="6">
                                <div class="no_data">
                                    <img src="https://image.flaticon.com/icons/svg/87/87980.svg"/>
                                    <p>문의 내역이 없습니다.</p>
                                </div>
                            </td>
                        </tr>
                    @endif
                    </tbody>
                </table>
            </div>
        </div>

        <div id="add_writing" class="overlay-wrap alert">
            <div class="writing_wrap">

                <div class="writing_box">

                    <div class="inner">
                        <div class="top clearfix">
                            <h1>문의하기</h1>
                            <button type="button" onclick="addWritingDisNone()"><img src="/assets/img/btn_close.png" alt="닫기 버튼"/></button>
                        </div>
                        <form method="POST" id="frm" name="frm" action="{{ route('questions.store') }}">
                            @csrf
                            <div class="cont">
                                <div class="form-group">
                                    <label for="name">이름/회사명</label>
                                    <input type="text"  class="form-control" name="name" value="{{ \Illuminate\Support\Facades\Auth::user()->name }}" autocomplete="off" placeholder="이름/회사명을 입력해주세요">
                                </div>
                                <div class="form-group">
                                    <label for="title">제목</label>
                                    <input type="text"  class="form-control" name="title" autocomplete="off" placeholder="제목을 입력해주세요">
                                </div>
                                <div class="form-group">
                                    <label for="context">문의내용</label>
                                    <textarea  class="form-control" style="resize: none;"  name="content" autocomplete="off" placeholder="내용을 입력해주세요"></textarea>
                                </div>
                                <div class="form-group form-inline">
                                    <p>
                                        <label for="phone">연락처</label>
                                        <input type="number" class="form-control" name="phone" value="{{ \Illuminate\Support\Facades\Auth::user()->phone }}"  autocomplete="off" placeholder="(ex. 01012345678910)">
                                    </p>
                                    <p>
                                        <label for="email">이메일</label>
                                        <input type="text"  class="form-control" name="email" value="{{ \Illuminate\Support\Facades\Auth::user()->email }}" autocomplete="off" placeholder="이메일을 입력해주세요">
                                    </p>

                                </div>
                            </div>
                            <div class="cont_sub">
                                <span class="checkbox" style="position: absolute; left: 0; top: 14px;">
                                    <input type="checkbox" id="Check_1" name="check" />
                                    <label for="Check_1"></label>
                                </span>
                                <label for="Check_1">
                                    <span class="txt">개인정보 수집 동의</span>
                                </label>
                                    <div class="context">
                                        <p>문의접수 및 처리를 위해 이메일, 연락처를 수집하고 접수된 내용은 6개월 동안 보관합니다.</p>
                                        <p>개인정보 수집 동의를 거부할 수 있으며, 거부 시 문의가 불가할 수 있습니다.</p>
                                    </div>

                            </div>
                            <div class="btn_box">
                                <button type="button" id="btn" name="btn">문의등록</button>
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>

    </div>

@include('questions.mobile')

@endsection

resources/views/questions/mobile.blade.php
@prepend('scripts')
    <script>
        $('#frm_mobile button[name=btn]').click(function(){
            if ($("#frm_mobile input[name=name]").val() == "") {
                alert('이름을 입력하세요.');
                return false;
            }

            if ($("#frm_mobile input[name=title]").val() == "") {
                alert('제목을 입력하세요.2');
                return false;
            }

            if ($("#frm_mobile [name=content]").val() == "") {
                alert('내용을 입력하세요.');
                return false;
            }

            if ($("#frm_mobile input[name=phone]").val() == "") {
                alert('연락처를 입력하세요.');
                return false;
            }

            if ($("#frm_mobile input[name=email]").val() == "") {
                alert('이메일을 입력하세요.');
                return false;
            }

            var sEmail = $("#frm_mobile input[name=email]").val();

            if (!validateEmail(sEmail)) {
                alert('잘못된 이메일 형식 입니다');
                return false;
            }

            if ($("#frm_mobile input:checkbox[name=check]").is(":checked") == false) {
                alert('개인정보 수집 동의 확인 후 가능합니다.');
                return false;
            }

            $('#frm_mobile').submit();
        });
    </script>

@endprepend

<div class="container-fluid flex-grow-1 container-p-y contact_us_mo">
    <div class="wrap">
        <div class="top clearfix">
            <p>문의하기
                <span class="txt">DMP9에게 궁금한 점을 쉽고 빠르게 찾아보세요.</span>
            </p>
            <button type="button" onclick="moAddWriting()">글쓰기</button>
        </div>
        <div class="cont">
            <div class="top">목록</div>
            <!--묶음-->
            @foreach($questions as $question)
            <ul>
                <li class="text_question">
                    <div class="text_01 form-inline">
                        <div>{{ $question['title'] }}</div>
                        <div><img src="./assets/img/icon_down_arrow.png" alt="아이콘 아래 화살표"/></div>
                    </div>
                    <div class="text_02 mt-2">
                        @if (!$question['answers']->isEmpty())
                            <div>답변완료</div>
                        @else
                            <div>답변대기</div>
                        @endif

                        <!-- <div><img src="./assets/img/icon_down_arrow.png" alt="아이콘 아래 화살표"/></div> -->
                    </div>
                </li>
                <li class="text_answer mt-3">
                    <div>
                        <span>질문</span>
                        {{ $question['content'] }}
                    </div>
                    @if (!$question['answers']->isEmpty())
                    <div class="mt-2">
                        <span>답변</span>
                        @foreach ($question['answers'] as $answer)
                            {{ $answer['content'] }}
                        @endforeach
                    </div>
                    @endif
                </li>
            </ul>
            @endforeach
            @if ($questions->isEmpty())
                <tr>
                    <td colspan="6">
                        <div class="no_data">
                            <img src="https://image.flaticon.com/icons/svg/87/87980.svg"/>
                            <p>문의 내역이 없습니다.</p>
                        </div>
                    </td>
                </tr>
            @endif

            <!--묶음-->
        </div>
    </div>

    <div id="mo_add_writing" class="overlay-wrap alert">
        <div class="writing_wrap">
            <div class="writing_box">
                <form method="POST" id="frm_mobile" name="frm_mobile" action="{{ route('questions.store') }}">
                    @csrf
                <div class="inner">
                    <div class="top clearfix">
                        <h1>문의하기</h1>
                        <button type="button" onclick="moAddWritingDisNone()"><img src="/assets/img/btn_close.png" alt="닫기 버튼"/></button>
                    </div>
                    <div class="cont">
                        <div class="form-group">
                            <label for="name">이름/회사명</label>
                            <input type="text"  class="form-control" name="name" value="{{ \Illuminate\Support\Facades\Auth::user()->name }}" autocomplete="off" placeholder="이름/회사명을 입력해주세요">
                        </div>
                        <div class="form-group">
                            <label for="title">제목</label>
                            <input type="text"  class="form-control" name="title" autocomplete="off" placeholder="제목을 입력해주세요">
                        </div>
                        <div class="form-group">
                            <label for="context">문의내용</label>
                            <textarea id="context" class="form-control" style="resize: none;" name="content" autocomplete="off" placeholder="내용을 입력해주세요"></textarea>
                        </div>
                        <div class="form-group">
                            <p>
                                <label for="phone">연락처</label>
                                <input type="number"  class="form-control" name="phone" value="{{ \Illuminate\Support\Facades\Auth::user()->phone }}" autocomplete="off" placeholder="연락처를 입력해주세요">
                            </p>
                            <p>
                                <label for="email">이메일</label>
                                <input type="text"  class="form-control" name="email" value="{{ \Illuminate\Support\Facades\Auth::user()->email }}" autocomplete="off" placeholder="이메일을 입력해주세요">
                            </p>

                        </div>
                        <div class="cont_sub">
                        <span class="checkbox" style="position: absolute; left: 0; top: 14px;">
                            <input type="checkbox" id="Check_2" name="check" />
                            <label for="Check_2"></label>
                        </span>
                            <span class="txt">개인정보 수집 동의</span>
                            <div class="context">
                                <p>문의접수 및 처리를 위해 이메일, 연락처를 수집하고 접수된 내용은 6개월 동안 보관합니다.</p>
                                <p>개인정보 수집 동의를 거부할 수 있으며, 거부 시 문의가 불가할 수 있습니다.</p>
                            </div>
                        </div>
                        <div class="btn_box">
                            <button type="button" name="btn">문의등록</button>
                        </div>
                    </div>

                </div>

                </form>
            </div>
        </div>
    </div>

</div>

resources/views/questions/show.blade.php
@extends('dashboard')

@section('content')

            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Questions Create</div>

                    <div class="card-body">



                        <div class="form-group row">
                            <label for="title" class="col-md-4 col-form-label text-md-right">Title</label>

                            <div class="col-md-6">
                                {{ $question['title'] }}
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="content" class="col-md-4 col-form-label text-md-right">Content</label>

                            <div class="col-md-6">
                                {{ $question['content'] }}
                            </div>
                        </div>


                        <a class="btn btn-primary" href="{{ route('questions.edit', $question['question_id']) }}" role="button">수정하기</a>

                        <form method="POST" action="{{ route('questions.destroy', $question['question_id']) }}">
                            @csrf
                            @method('DELETE')

                            <button type="submit" class="btn btn-danger">
                                삭제
                            </button>
                        </form>
                    </div>
                </div>
            </div>

@endsection