routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Auth;

Route::get('/', function () {return view('welcome');});

Auth::routes();

// 회원가입
Route::get('/sign_up_type', function() { return view('sign.sign_up_type');});
Route::post('/sign_up_terms', function(\Illuminate\Http\Request $request) {
    return view('sign.sign_up_terms', compact('request'));
});
Route::post('/sign_up_register', function(\Illuminate\Http\Request $request) {
    return view('sign.sign_up_register', compact('request'));
});
Route::post('/sign_up_register_company', function(\Illuminate\Http\Request $request) {
    return view('sign.sign_up_register_company', compact('request'));
});

Route::get('/terms_01', function() {
    return view('sign.terms_01');
});

Route::get('/terms_02', function() {
    return view('sign.terms_02');
});

Route::get('/sign_up_type', function() {
    return view('sign.sign_up_type');
});

Route::get('/sign_up_find_id', function() {
    return view('sign.sign_up_find_id');
});

Route::get('/sign_up_find_pw', function() {
    return view('sign.sign_up_find_pw');
});

Route::post('/sign_up_find_new_pw', function(\Illuminate\Http\Request $request) {

    if (!$request->user_id) {
        return response()->redirectTo('/');
    }

    return view('sign.sign_up_find_new_pw');
});

Route::get('/sign_up_finish_sign_up', function() {
    return view('sign.sign_up_finish_sign_up');
});

Route::post('/ajaxIdCheckRequest', 'UserController@id_check')->name('Users.idcheckrequest');
Route::post('/ajaxSignUpFindId', 'UserController@SingUpFindId')->name('Users.SingUpFindId');
Route::post('/ajaxSingUpFindPassword', 'UserController@SingUpFindPassWord')->name('Users.SingUpFindPassword');

Route::post('/ajaxSingUpNewPw', 'UserController@SingUpNewPw')->name('Users.SingUpNewPw');

Route::post('/ajaxSmsSend', 'SmsController@SmsSend')->name('SmsSend');
Route::post('/ajaxSmsCheck', 'SmsController@SmsCheck')->name('SmsCheck');


// 인증 예외 처리
Route::get('/approved', function() {
    Auth::logout();
    return view('approved');
})->name('approved');

// 권한 예외 처리
Route::get('/role', function() {
    Auth::logout();
    return view('role');
})->name('role');

Route::post('/ajaxContactusCreate', 'ContactsusController@store')->name('Contactsus.create');

Route::post('/ajaxPayCallback', 'PaymentsController@payCallback')->name('Payments.paycallback');

Route::middleware(['auth', 'approved','role'])->group( function () {

    Route::get('/dashboard', 'DashBoardController@index')->name('dashboard.index');

    // 마이데이터(order)
    Route::resource('goods' , 'GoodsController');
    Route::resource('carts' , 'CartController');
    Route::post('/ajaxFindCart' , 'CartController@findById')->name('carts.findById');


    // 마이데이터 플랫폼(option)
    Route::post('/ajaxOptionAdd','OptionController@optionAdd')->name('Option.add');
    Route::post('/ajaxOptionSave','OptionController@optionSave')->name('Option.save');
    Route::post('/ajaxOptionUploadRequest','OptionController@optionUploadRequest')->name('Option.updateload');

    // payment
    Route::post('/ajaxPayRequest', 'PaymentsController@payRequest')->name('Payments.payrequest');
    Route::post('/ajaxPayReturn', 'PaymentsController@payReturn')->name('Payments.payreturn');

    Route::get('/ajaxPayCancel', 'PaymentsController@payCancel')->name('Payments.payCancel');

    // 자주묻는질문(faq)
    Route::resources(['faqs' => 'FaqController']);

    // 문의및답변(qna)
    Route::resources(['questions' => 'QuestionController']);

    // 세금계산서요청(tax)
    Route::get('taxs', function () { return view('taxs.index'); });

    // 내정보 수정(users)
    Route::get('users', function () { return view('users.index'); });

    Route::get('users/confirm', 'UserController@confirm_index')->name('confirm_index');
    Route::post('users/confirm_check', 'UserController@confirm_check')->name('confirm_check');
    Route::post('my_show', 'UserController@my_show')->name('my_show');
    Route::post('my_update', 'UserController@my_update')->name('my_update');
    Route::get('file_download/{file_name}', 'UserController@file_download')->name('file_download');

    // 주문내역
    Route::get('/history', 'OrderController@history')->name('orders_history');
    Route::post('/ajaxFindOrder', 'OrderController@findById')->name('orders.findById');
    Route::post('/ajaxTaxState', 'OrderController@taxstate')->name('tax_state');

    // payment_test_page
    Route::get('/payment', function () {
        return view('payment');
    })->name('Payments.index');


});

app/Cart.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{
    protected $guarded = ['*','id'];

    CONST STATE_1 = 1;      // 확인중
    CONST STATE_2 = 2;      // 결제 대기중
    CONST STATE_3 = 3;      // 결제 완료
    CONST STATE_4 = 4;      // 데이터 추출중
    CONST STATE_5 = 5;      // 데이터 완료

    public function format()
    {
        return [
            'cart_id' => $this->id,
            'user_id' => $this->user,
            'goods_id' => $this->goods,
            'order_id' => $this->orders,
            'state' => $this->state,
            'buy_date' => $this->buy_date,
            'options_id' => $this->options,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at
        ];
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function goods()
    {
        return $this->belongsTo(Goods::class);
    }

    public function orders()
    {
        return $this->hasMany(Order::class, 'order_no','order_no');
    }

    public function options()
    {
        return $this->hasMany(Option::class)->orderBy('id','desc');
    }


    public function getMarkPriceAttribute()
    {
        return number_format($this->goods->buy_price);
    }
}

app/Order.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Order extends Model
{

    CONST ORDER_STATE_0 = 0;      // 결제전
    CONST ORDER_STATE_1 = 1;      // 결제완료

    CONST TAX_STATE_1 = 1;  // 계산서 요청가능 (미발행)
    CONST TAX_STATE_2 = 2;  // 계산서 요청신청 (확인중)
    CONST TAX_STATE_3 = 3;  // 계산서 신청완료 (발행)

    protected $guarded = ['*','id'];

    public function format()
    {
        return [
            'order_id' => $this->id,
            'user_id' => $this->user,
            'payment_id' => $this->payment_id,
            'order_no' => $this->order_no,
            'order_name' => $this->order_name,
            'goods_info' => $this->goods_info,
            'state' => $this->state,
            'tax_state' => $this->tax_state,
            'total_count' => $this->total_count,
            'total_price' => $this->total_price,
            'created_at' => $this->created_at->format('Y-m-d'),
            'updated_at' => $this->updated_at->format('Y-m-d')
        ];
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/OrderController.php
<?php

namespace App\Http\Controllers;


use App\Repositories\OrderRepositoryInterface;
use Illuminate\Http\Request;

class OrderController extends Controller
{
    private $orderRepository;

    public function __construct(OrderRepositoryInterface $orderRepository)
    {
        $this->orderRepository = $orderRepository;
    }

    public function history()
    {
        $orders = $this->orderRepository->all();

        if (auth()->user()->role == "personal") {
            $txt = "영수증";
        } else if (auth()->user()->role == "company") {
            $txt = "계산서";
        }

        return view('orders.history', compact('orders', 'txt'));
    }

    public function taxstate(Request $request)
    {
        $request_data = json_decode($request->data);

        $return_result = $this->orderRepository->taxstate_update($request_data);

        if (!$return_result) {
            $result['result'] = "error";
            $result['error_message'] = "등록되어 있는 계산서가 없습니다.";
            $response = response()->json($result, 200, ['Content-type'=> 'application/json; charset=utf-8'], JSON_UNESCAPED_UNICODE);
        } else {
            $result['result'] = "success";
            $response = response()->json($result, 200, ['Content-type'=> 'application/json; charset=utf-8'], JSON_UNESCAPED_UNICODE);
        }

        return $response;
    }

    public function findById(Request $request)
    {
        $request_data = json_decode($request->data);

        $return_result = $this->orderRepository->findById($request_data->order_id);

        if (!$return_result) {
            $result['result'] = "error";
            $result['error_message'] = "등록되어 있는 계산서가 없습니다.";
            $response = response()->json($result, 200, ['Content-type'=> 'application/json; charset=utf-8'], JSON_UNESCAPED_UNICODE);
        } else {
            $result['result'] = "success";
            $result['order_info'] = $return_result;
            $response = response()->json($result, 200, ['Content-type'=> 'application/json; charset=utf-8'], JSON_UNESCAPED_UNICODE);
        }

        return $response;
    }
}

resources/views/orders/create.blade.php
@extends('dashboard')

@section('content')

                    <div class="card-header">Order Create</div>

                    <div class="card-body">

                        <form method="POST" action="{{ route('orders.store') }}">
                            @csrf


                            <div class="form-group row">
                                <label for="content" class="col-md-4 col-form-label text-md-right">데이터명</label>

                                <div class="col-md-6">
                                    <input id="data_name" type="text" class="form-control  @error('data_name') is-invalid @enderror" name="data_name" value="" autocomplete="data_name">

                                    @error('data_name')
                                    <span class="text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label for="data_count" class="col-md-4 col-form-label text-md-right">데이터항목</label>

                                <div class="col-md-6">
{{--                                    <input id="data_category" type="text" class="form-control  @error('data_category') is-invalid @enderror" name="data_category" value="" autocomplete="data_category">--}}
                                    <select id="data_category" type="text" class="form-control @error('data_category') is-invalid @enderror" name="data_category" >
                                        <option value=""></option>
                                        <option value="A">A</option>
                                        <option value="B">B</option>
                                    </select>

                                    @error('data_category')
                                    <span class="text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        저장하기
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>


@endsection

resources/views/orders/edit.blade.php
@extends('dashboard')

@section('content')


    <div class="col-md-8">
        <div class="card">
            <div class="card-header">Order Create</div>

            <div class="card-body">

                <form method="POST" action="{{ route('orders.update', $order->id) }}">
                    @csrf
                    @method('PUT')



                    <div class="form-group row">
                        <label for="content" class="col-md-4 col-form-label text-md-right">데이터명</label>

                        <div class="col-md-6">
                            <input id="data_name" type="text" class="form-control  @error('data_name') is-invalid @enderror" name="data_name" value="{{ $order->data_name }}" autocomplete="data_name">

                            @error('data_name')
                            <span class="text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>



                    <div class="form-group row">
                        <label for="data_count" class="col-md-4 col-form-label text-md-right">데이터수</label>

                        <div class="col-md-6">
                            <input id="data_count" type="text" class="form-control  @error('data_count') is-invalid @enderror" name="data_count" value="{{ $order->data_count }}" autocomplete="data_count">

                            @error('data_count')
                            <span class="text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="buy_price" class="col-md-4 col-form-label text-md-right">구매가격</label>

                        <div class="col-md-6">
                            <input id="buy_price" type="text" class="form-control  @error('buy_price') is-invalid @enderror" name="buy_price" value="{{ $order->buy_price }}" autocomplete="buy_price">

                            @error('buy_price')
                            <span class="text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>


                    <div class="form-group row">
                        <label for="buy_date" class="col-md-4 col-form-label text-md-right">구매일</label>

                        <div class="col-md-6">
                            <input id="buy_date" type="text" class="form-control  @error('buy_date') is-invalid @enderror" name="buy_date" value="{{ $order->buy_date }}" autocomplete="buy_date">

                            @error('buy_date')
                            <span class="text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="expiration_date" class="col-md-4 col-form-label text-md-right">유효기간</label>

                        <div class="col-md-6">
                            <input id="expiration_date" type="text" class="form-control  @error('expiration_date') is-invalid @enderror" name="expiration_date" value="{{ $order->expiration_date }}" autocomplete="expiration_date">

                            @error('expiration_date')
                            <span class="text-danger" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                            @enderror
                        </div>
                    </div>

                    <div class="form-group row mb-0">
                        <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                저장하기
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


@endsection

resources/views/orders/index.blade.php
@extends('layouts.backend')

@prepend('scripts')
    <script>
    $(function() {
        $("input[name=sel]").click(function() {
            var total_count=0;
            var total_price=0;
            $("input[name=sel]:checked").each(function() {
                total_count += $(this).data("count");
                total_price += $(this).data("price");
            });
            $("span[name=total_price]").text(total_price);
        });


        $(".createBtn").click(function() {
            $("form[name='registerForm']").validate({
                rules: {
                    advertiser: "required",
                    "data_types[]": {
                        required: true,
                        minlength: 1
                    },
                    data_target:"required",
                    data_name:"required",
                    data_category:"required",
                },
                messages: {
                },

                errorPlacement: function(error, element){
                },
                highlight: function (element, required) {
                        $(element).css('border', '2px solid #FDADAF');
                },
            });
        });


        $(".checkBtn").click(function(){
            var object = new Array();
            var tr = $(this).parent().parent().parent().parent();
            var td = tr.children();
            var product_id = tr.find("input[type=hidden]").val();

            object.push(product_id);
            object.push(td.eq(3).text());
            object.push(td.eq(4).text());
            object.push(td.eq(5).text().replace("원","").replace(",","").trim());
            object.push(td.eq(6).text());
            object.push(td.eq(7).text());

            $.ajax({
                headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                url: "{{ route('Payments.payrequest') }}",
                method: "POST",
                dataType: "json",
                data: {'data': object},
                success: function (data) {
                    if (data['error']) {
                        var JSONArray = JSON.parse(data['error']);
                        alert(JSONArray['message']);
                    } else {
                        var JSONArray = JSON.parse(data['success']);
                        window.open(JSONArray['online_url'],"페이레터","width=800, height=700, toolbar=no, menubar=no, scrollbars=no, resizable=yes");
                    }
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    alert('결제 실패');
                }
            });
        });

        $('button[name="orderBtn"], button[name="searchBtn"]').click(function(){
            $('input[name="sort"]').val($(this).attr("data-type"));
            $('[name="frm"]').submit();
        })

        $(".new_buy").click(function() {
            var ids = new Array();
            var total_price=0;
            $("input[name=sel]:checked").each(function() {
                ids.push($(this).val());
                total_price += $(this).data("price");
            });

            if (ids.length > 0) {
                var data = new Object() ;
                data.ids = ids;
                data.price = total_price;
                var jsonData = JSON.stringify(data);
                console.log(jsonData);

                $.ajax({
                    headers: {'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')},
                    url: "{{ route('Payments.payrequest') }}",
                    method: "POST",
                    dataType: "json",
                    data: {'data': jsonData},
                    success: function (data) {
                        if (data['error']) {
                            var JSONArray = JSON.parse(data['error']);
                            alert(JSONArray['message']);
                        } else {
                            var JSONArray = JSON.parse(data['success']);
                            window.open(JSONArray['online_url'],"페이레터","width=800, height=700, toolbar=no, menubar=no, scrollbars=no, resizable=yes");
                        }
                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        console.log('결제 실패');
                    }
                });



            } else {
                console.log("구매 데이터를 선택 하세요.");
            }
        });

    });
    </script>
@endprepend

@section('content')
<!-- content : start-->
<div class="container-fluid flex-grow-1 container-p-y mydata_main">

    <form method="get" name="frm" onsubmit="return true" action="{{ route('orders.index') }}" >
        <input type="hidden" name="sort" value="">

        <div class="cont_top_wrap clearfix">
            <div class="cont_search_bar">
                <div class="form-group">
                    <div class="input-group">
                        <input type="text" class="form-control" name="sch" placeholder="데이터명 검색" value="{{ $sch }}">
                        <span class="input-group-append">
                            <button class="btn" name="searchBtn" type="button">
                                <img src="/img/btn_search.png" alt="검색 버튼 이미지"/>
                            </button>
                        </span>
                    </div>
                </div>
            </div>
        </div>

        <div class="cont_manu_wrap clearfix">
            <div class="top clearfix"style="display:inline-grid" >
                <button type="button" onclick="addWriting()" class="add_btn">데이터 등록</button> <!--가-->
            </div>
            <div class="top clearfix"style="display:inline-grid" >
                <button type="button" class="add_btn new_buy">구매</button>
            </div>

            <ul class="form-inline">
                <li><button type="button" name="orderBtn" data-type="id" >구매순</button></li>
                <li><button type="button" name="orderBtn" data-type="updated_at" >업데이트순</button></li>
                <li><button type="button" name="orderBtn" data-type="data_name" >데이터순</button></li>
                <li><button type="button" name="orderBtn" data-type="buy_price" >금액순</button></li>
                <li><button type="button" name="orderBtn" data-type="expiration_date" >유효기간순</button></li>
            </ul>
        </div>
    </form>
    <table class="table">
        <colgroup>
            <col width="40px">
            <col width="40px">
            <col width="60px">
            <col width="50px">
            <col width="50px">
            <col width="50px">
            <col width="50px">
            <col width="50px">
            <col width="75px">
        </colgroup>
        <thead class="thead-light">
        <tr>
            <th></th>
            <th>상태</th>
            <th>광고형태</th>
            <th>데이터명</th>
            <th>데이터수</th>
            <th>구매가격</th>
            <th>구매일</th>
            <th>유효기간</th>
            <th></th> <!--빈영역-->
        </tr>
        </thead>
        <tbody>
        @foreach($orders as $order)
            <tr>
                <input type="hidden" name="" value="{{ $order->id }}">
                <td>
                    @if ($order->state === 3)
                        <input type="checkbox" name="sel" value="{{ $order->id }}" data-count="" data-price="{{ $order->buy_price }}">
                    @else
                        <input type="checkbox" name="sel" value="{{ $order->id }}" disabled>
                    @endif
                </td>
                <td>
                    <div class="status_box">
                    @if ($order->state === 1)
                        요청중
                    @elseif ($order->state === 2)
                        추출중
                    @elseif ($order->state === 3)
                        승인요청
                    @elseif ($order->state === 4)
                        결제완료
                    @endif
                    </div>
                </td>
                <td>
                    <ul>

                    </ul>
                </td>
                <td>{{ $order->data_name }}</td>
                <td>{{ $order->data_count }}</td>
                <td>
                    @if (isset($order->buy_price))
                        {{$order->mark_price}} 원</td>
                    @endif
                </td>
                <td>{{ $order->buy_date }}</td>
                <td>{{ $order->expiration_date->format("Y-m-d") }}</td>
                <td>
                    <ul>
                        <li>
                            @if ($order->state === 3)
                                <button type="button" class="checkBtn" >결제하기 ></button>
                            @endif
                        </li>
                        <li><button type="button" onclick="location.href='/contact_us.html'">문의하기 ></button></li>
                    </ul>
                </td>
            </tr>
        @endforeach
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
                <td><span name="total_count">0</span></td>
                <td><span name="total_price">0</span></td>
                <td></td>
                <td></td>
                <td></td> <!--빈영역-->
            </tr>
        </tbody>
    </table>

    <!--추가-->
    <div id="add_writing" class="overlay-wrap alert">
        <div class="writing_wrap">
            <div class="writing_box">
                <form name="registerForm" method="POST" action="{{ route('goods.store') }}">
                    @csrf
                    <div class="inner">
                        <div class="top clearfix">
                            <h1>데이터 요청하기</h1>
                            <button type="button" onclick="addWritingDisNone()"><img src="/img/btn_close.png" alt="닫기 버튼"/></button>
                        </div>
                        <div class="cont">
                            <div class="form-group form-inline">
                                <label>광고주</label>
                                <input type="text" class="form-control  {{ $errors->has('advertiser') ? 'is-invalid' : '' }}" name="advertiser" placeholder="업종 & 광고주명 기입" value="{{ old('title') }}" >
                                @if ($errors->has('advertiser'))
                                    <div class="invalid-feedback">
                                        <strong>{{ $errors->first('advertiser') }}</strong>
                                    </div>
                                @endif
                            </div>
                            <div class="form-group form-inline">
                                <label>주로 쓰는 플랫폼 유형</label>
                                <div class="checkbox_wrap">
                                    <input type="checkbox" name="data_types[]" value="kakao"> 카카오
                                    <input type="checkbox" name="data_types[]" value="naver"> 네이버
                                    <input type="checkbox" name="data_types[]" value="facebook"> 페이스북
                                    <input type="checkbox" name="data_types[]" value="instagram"> 인스타그램
                                </div>
                            </div>
                            <div class="form-group form-inline">
                                <label>타겟 유형</label>
                                <div class="target_wrap">
                                    <input type="radio" name="data_target" value="app"> App
                                    <input type="radio" name="data_target" value="local"> 위치
                                    <input type="radio" name="data_target" value="applocal"> App + 위치
                                </div>
                            </div>
                            <div class="form-group form-inline">
                                <label>데이터 명</label>
                                <input type="text" class="form-control data_input" name="data_name" placeholder="데이터 명 기입">
                            </div>
                            <div class="form-group form-inline">
                                <label>데이터 항목</label>
                                <select class="data_wrap" name="data_category">
                                    <option value=""></option>
                                    <option value="A">A</option>
                                    <option value="B">B</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <textarea class="form-control" placeholder="원하는 타겟 설명" name="data_content"></textarea>
                            </div>
                        </div>

                        <div class="cont_sub">
                            <ul>
                                <li class="mb-2">타겟 구매시 주의사항</li>
                                <li>* 기본 구매 활용 기간은 1개월 입니다.</li>
                                <li>* 데이터 업데이트 요청은 활용기간내에만 가능합니다. (최대 3회 / 구매시점으로부터 1개월 내 가능)</li>
                                <li>* 특정 앱 지정 데이터 판매 불가 (트정 경쟁사 데이터만 구매 요청시 거절 될 수 있습니다.</li>
                                <li>* 불법적 활용 가능한 데이터 판매 불가 (도박, 성인 등)</li>
                            </ul>
                        </div>
                        <div class="btn_box">
{{--                            <button type="submit" onclick="addWritingDisNone()">요청하기</button>--}}
                            <button type="submit"class="createBtn">요청하기</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!--추가-->
</div>
<!-- content : end-->
@endsection